### ISSUE TITLE
Compiler JAR version ?

### ISSUE THREAD

**Issue by TheTonyk** [games647/LambdaAttack#1]
Hello,

It's possible to get a jar of your LambaAttack for 1.8.8 ?
I've somes strange issues to compile it.

Thanks !

**Comment by games647** [comment]
It's a very minimalistic project. Currently it can only connect to servers.

**Comment by games647** [comment]
It would be enough to change the dependency version in the pom.xml file to 

```xml
<version>1.8.8-SNAPSHOT</version>
```

instead of 
```xml
<version>1.9-SNAPSHOT</version>
```

**Comment by TheTonyk** [comment]
Oh okay, I try to do a stress test on my server with bots but I can't find any tools to do that
