### ISSUE TITLE
Support for console?

### ISSUE THREAD

**Issue by OfficialAName** [games647/LambdaAttack#11]
Hello, it's me again :), i was busy & i couldn't add myself a console version of this, could you release one?

**Comment by games647** [comment]
Why is this required. I don't see any good reasons for that.

**Comment by OfficialAName** [comment]
I want it to run it from a script for my server, to test my plugin that i'm currently trying to release a new version, but deathbot is full of "wait 5 secs" each time i stop the attack. Here is the link for my plugin if you don't trust me ;( https://www.spigotmc.org/resources/authors/imkermit.206308/

**Comment by games647** [comment]
I think it's a lot easier and better to write unit tests and make only system tests with GUI.

**Comment by OfficialAName** [comment]
oh, ok then :)
