### ISSUE TITLE
1.8 Connection issue

### ISSUE THREAD

**Issue by stuntguy3000** [games647/LambdaAttack#13]
Disconnected: io.netty.handler.codec.DecoderException: java.lang.NoSuchMethodError: org.spacehq.opennbt.NBTIO.readTag(Ljava/io/DataInputStream;)Lorg/spacehq/opennbt/tag/builtin/Tag;

Server is on 1.8.8 (using custom name tags). Any ideas?

**Comment by games647** [comment]
It's because 1.11.2 version of McProtocolLib uses OpenNBT 1.1 and this version overrides the older one while shading the dependencies into the jar.
