### ISSUE TITLE
Build version with 1.12 support

### ISSUE THREAD

**Issue by ams0** [games647/LambdaAttack#20]
https://github.com/games647/LambdaAttack/releases still contains the version without 1.12 support, could you please build and publish the binary for the newest Minecraft Server? I tried to build it myself but I really suck at Java..(perhaps you can amend the README with instructions how to build?)

Thanks!

**Comment by games647** [comment]
Building it isn't that hard, because it uses Maven which fetches all necessary libraries automatically from a central repository. Nevertheless I uploaded the version and added a build guide - maybe it helps you.
