### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by OfficialAName** [games647/LambdaAttack#3]
Can you add version selector? that would be great for servers that are 1.7;1.8;1.9! :+1: 
EDIT: Also can you add a download link too?

**Comment by games647** [comment]
>Also can you add a download link too?

I just thought I could use spigot for providing downloads, because there is already a stress tester there.

**Comment by games647** [comment]
>Can you add version selector? that would be great for servers that are 1.7;1.8;1.9

I think that would work. It would be just ~300kB additional file size for each version

**Comment by OfficialAName** [comment]
ok, thank you :+1: !
