### ISSUE TITLE
How to launch the GUI ?

### ISSUE THREAD

**Issue by ninijule** [games647/LambdaAttack#38]
Hello, 

I just want to have the options to launch the GUI but i don't have find this in the code.

Ty

**Comment by games647** [comment]
So what do you want to achieve, launching the GUI from code?

**Comment by Lqxys** [comment]
i think yes

**Comment by ninijule** [comment]
in reality i would use some proxies file, i have to stress test my own server. 
But i don't find the option to to specify the file proxies.

**Comment by leowww213122** [comment]
español: hola! apenas lo descargue y lo abrí  y me salio UN error Podías alegrar eso?
Ingles: Hi! I just downloaded it and opened it and I got an error. Could you brighten that up?

Captura/capture: https://prnt.sc/ugghy7
