### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by OfficialAName** [games647/LambdaAttack#4]
Proxy doesn't work. When i load the proxy file and click start, it wont do anything!

**Comment by games647** [comment]
What does the log say about it?

**Comment by OfficialAName** [comment]
nothing

**Comment by OfficialAName** [comment]
*bump*, is there any fix ?

**Comment by games647** [comment]
I'm currently very busy. I'm going to work on it next week.

**Comment by OfficialAName** [comment]
ok

**Comment by games647** [comment]
Does it loaded the proxies? Do you choosed SOCKS4/5 proxies?

Do you see something like
>1:25 PM INFO [LambdaAttack] Opening: filename
1:25 PM INFO [LambdaAttack] Loaded 37.220 proxies

**Comment by OfficialAName** [comment]
yes i see. It loads them but it doesn't connect to server or anything, i just hit start and it does nothing. 

![image](https://cloud.githubusercontent.com/assets/18629391/17481059/a7c7081a-5d83-11e6-9857-81c5fe3cd066.png)

**Comment by OfficialAName** [comment]
Lol now it gives : 
![image](https://cloud.githubusercontent.com/assets/18629391/17481068/b64f3aa6-5d83-11e6-88d4-f68e7a9a3aec.png)
 and the proxies are fresh!

**Comment by games647** [comment]
Are you sure. They are SOCKS proxies?

**Comment by OfficialAName** [comment]
im 100 percent sure. tried with different list and socks 5 proxies, still doesnt work..

**Comment by games647** [comment]
That's weird, because I tried it using a socks proxy list (12.000 proxies). I additionally tested the proxies using a proxy checker and found 10 working proxies. One proxy timed out, but the others worked when using LambdaAttack.

**Comment by OfficialAName** [comment]
idk why it wont work.. seriously :( i just want it to work just to use the cmd version of it so that i can use it on my linux server :( (tested it on windows 10 not linux)

**Comment by games647** [comment]
You could try this proxy as an example. It's currently working for me.

92.222.78.130:8080

**Comment by OfficialAName** [comment]
`Aug 08, 2016 7:01:17 PM com.github.games647.lambdaattack.gui.MainGui lambda$3
INFO: Loaded 1 proxies
Aug 08, 2016 7:01:19 PM com.github.games647.lambdaattack.gui.MainGui lambda$4
SEVERE: null
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.github.games647.lambdaattack.LambdaAttack.start(LambdaAttack.java:31)
	at com.github.games647.lambdaattack.gui.MainGui.lambda$4(MainGui.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

`

**Comment by games647** [comment]
Ah right. Just duplicate it four times for now.

**Comment by games647** [comment]
I found a bug that the proxy list rotation doesn't worked. Basically the program used the same first couple of proxies multiple times.

**Comment by games647** [comment]
It should be fixed now.

**Comment by games647** [comment]
The PacketLib repository was updated. Now it should display the correct error. Steveice10/PacketLib#13

So I'm closing this one.
