### ISSUE TITLE
Can't complete installation (lamdbaattack-version folder fails)

### ISSUE THREAD

**Issue by ZDavePlays** [games647/LambdaAttack#44]
Hello,
I'm trying to install this, but I keep getting an error when going through the lamdbaattack-version folder.
I installed apache maven successfully, I set up the paths as well, installed the latest version of java, installed MCProtocolLib(Don't know if it was needed but still did just in case, and this one did install without error), I tried everything, I keep rerunning the command but it can never install this folder.

Any help would be appreciated!
Here's the output:

<details>
<summary>Cmd output</summary>
Microsoft Windows [Version 10.0.18362.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Groot>cd C:\Users\Groot\Desktop\LambdaAttack-master

C:\Users\Groot\Desktop\LambdaAttack-master>mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] LambdaAttack                                                       [pom]
[INFO] lambdaattack-version                                               [jar]
[INFO] lambdaattack-version-1-11                                          [jar]
[INFO] lambdaattack-version-1-12                                          [jar]
[INFO] lambdaattack-version-1-14                                          [jar]
[INFO] lambdaattack-version-1-15                                          [jar]
[INFO] lambdaattack-core                                                  [jar]
[INFO]
[INFO] ------------------< com.github.games647:lambdaattack >------------------
[INFO] Building LambdaAttack 2.4.0                                        [1/7]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lambdaattack ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ lambdaattack ---
[INFO] Installing C:\Users\Groot\Desktop\LambdaAttack-master\pom.xml to C:\Users\Groot\.m2\repository\com\github\games647\lambdaattack\2.4.0\lambdaattack-2.4.0.pom
[INFO]
[INFO] --------------< com.github.games647:lambdaattack-version >--------------
[INFO] Building lambdaattack-version 2.4.0                                [2/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lambdaattack-version ---
[INFO] Deleting C:\Users\Groot\Desktop\LambdaAttack-master\version\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ lambdaattack-version ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Groot\Desktop\LambdaAttack-master\version\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ lambdaattack-version ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\Users\Groot\Desktop\LambdaAttack-master\version\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for LambdaAttack 2.4.0:
[INFO]
[INFO] LambdaAttack ....................................... SUCCESS [  0.328 s]
[INFO] lambdaattack-version ............................... FAILURE [  0.618 s]
[INFO] lambdaattack-version-1-11 .......................... SKIPPED
[INFO] lambdaattack-version-1-12 .......................... SKIPPED
[INFO] lambdaattack-version-1-14 .......................... SKIPPED
[INFO] lambdaattack-version-1-15 .......................... SKIPPED
[INFO] lambdaattack-core .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.108 s
[INFO] Finished at: 2020-05-19T12:41:03-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project lambdaattack-version: Fatal error compiling: invalid target release: 1.9 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :lambdaattack-version

C:\Users\Groot\Desktop\LambdaAttack-master>
</details>

Here's the output when doing mvn -e
<details>
<summary>mvn -e output</summary>
C:\Users\Groot\Desktop\LambdaAttack-master>mvn -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] LambdaAttack                                                       [pom]
[INFO] lambdaattack-version                                               [jar]
[INFO] lambdaattack-version-1-11                                          [jar]
[INFO] lambdaattack-version-1-12                                          [jar]
[INFO] lambdaattack-version-1-14                                          [jar]
[INFO] lambdaattack-version-1-15                                          [jar]
[INFO] lambdaattack-core                                                  [jar]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for LambdaAttack 2.4.0:
[INFO]
[INFO] LambdaAttack ....................................... SKIPPED
[INFO] lambdaattack-version ............................... SKIPPED
[INFO] lambdaattack-version-1-11 .......................... SKIPPED
[INFO] lambdaattack-version-1-12 .......................... SKIPPED
[INFO] lambdaattack-version-1-14 .......................... SKIPPED
[INFO] lambdaattack-version-1-15 .......................... SKIPPED
[INFO] lambdaattack-core .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.149 s
[INFO] Finished at: 2020-05-19T12:59:19-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
org.apache.maven.lifecycle.NoGoalSpecifiedException: No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy.
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:97)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
</details>

**Comment by games647** [comment]
You don't have Java 9 installed.

**Comment by ZDavePlays** [comment]
> You don't have Java 9 or higher installed.

Yup, that was it! I forgot to update the path from the old JDK to the new JDK.
Thank you very much!
