### ISSUE TITLE
Cannot launch last version

### ISSUE THREAD

**Issue by XsplitS** [games647/LambdaAttack#47]
https://i.imgur.com/UqGjY6R.png
https://i.imgur.com/xAA536x.png
https://i.imgur.com/dAHsruh.png

**Comment by games647** [comment]
Your Java version is outdated.

**Comment by XsplitS** [comment]
Okay thx.
Please insert the link in the readme.txt.
It's working with: Java SE 9.0.4

**Comment by games647** [comment]
>Please insert the link in the readme.txt.
 

There are multiple different JVM implementations. There is OpenDJK, J9, GraalVM and so. The language level java 9 should be enough.
