### ISSUE TITLE
Update To 1.16

### ISSUE THREAD

**Issue by RocketNinja15** [games647/LambdaAttack#51]
The title says it all :)

**Comment by CrushedPixel** [comment]
It's not particularly difficult to update this tool to a new Minecraft version - see my older PR adding support for Minecraft 1.15: #35 

Good luck!

**Comment by XfedeX** [comment]
We NEED it!

**Comment by just456** [comment]
> 
> 
> It's not particularly difficult to update this tool to a new Minecraft version - see my older PR adding support for Minecraft 1.15: #35
> 
> Good luck!

@CrushedPixel I can't make it work
Getting `BUILD FAILURE`

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project lambdaattack-core: Compilation failure: Compilation failure:
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[7,54] package com.github.steveice10.mc.protocol.data.message does not exist
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[8,62] package com.github.steveice10.mc.protocol.packet.ingame.server does not exist
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[9,62] package com.github.steveice10.mc.protocol.packet.ingame.server does not exist
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[10,76] package com.github.steveice10.mc.protocol.packet.ingame.server.entity.player does not exist
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[11,76] package com.github.steveice10.mc.protocol.packet.ingame.server.entity.player does not exist
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/Bot.java:[47,93] incompatible types: java.net.Proxy cannot be converted to com.github.steveice10.packetlib.ProxyInfo
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[22,49] cannot find symbol
[ERROR]   symbol:   class ServerChatPacket
[ERROR]   location: class com.github.games647.lambdaattack.bot.listener.SessionListener116
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[23,13] cannot find symbol
[ERROR]   symbol:   class ServerChatPacket
[ERROR]   location: class com.github.games647.lambdaattack.bot.listener.SessionListener116
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[24,13] cannot find symbol
[ERROR]   symbol:   class Message
[ERROR]   location: class com.github.games647.lambdaattack.bot.listener.SessionListener116
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[26,56] cannot find symbol
[ERROR]   symbol:   class ServerPlayerPositionRotationPacket
[ERROR]   location: class com.github.games647.lambdaattack.bot.listener.SessionListener116
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[27,13] cannot find symbol
[ERROR]   symbol:   class ServerPlayerPositionRotationPacket
[ERROR]   location: class com.github.games647.lambdaattack.bot.listener.SessionListener116
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[36,56] cannot find symbol
[ERROR]   symbol:   class ServerPlayerHealthPacket
[ERROR]   location: class com.github.games647.lambdaattack.bot.listener.SessionListener116
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[37,13] cannot find symbol
[ERROR]   symbol:   class ServerPlayerHealthPacket
[ERROR]   location: class com.github.games647.lambdaattack.bot.listener.SessionListener116
[ERROR] /C:/Users/justi/Downloads/Compressed/apache-maven-3.6.3/bin/core/src/main/java/com/github/games647/lambdaattack/bot/listener/SessionListener116.java:[40,56] cannot find symbol
[ERROR]   symbol:   class ServerJoinGamePacket
[ERROR]   location: class com.github.games647.lambdaattack.bot.listener.SessionListener116`

**Comment by TuxCoding** [comment]
Thanks to the help of #53, it was recently added. @just456 How do you tried to build the project?

**Comment by ghost** [comment]
> 
> 
> Thanks to the help of #53, it was recently added. @just456 How do you tried to build the project?

I tried with maven

**Comment by ghost** [comment]
> 
> 
> Thanks to the help of #53, it was recently added. @just456 How do you tried to build the project?

Without any modifications everything builds correctly, when I add 116 configurations it does not build
