### ISSUE TITLE
import org.spacehq.mc.protocol.v1_10.packet.ingame.client.ClientChatPacket;

### ISSUE THREAD

**Issue by OfficialAName** [games647/LambdaAttack#6]
import org.spacehq.mc.protocol.v1_10.packet.ingame.client.ClientChatPacket;

I get this error, i have installed mcauthlib-1.0 ; opennbt-1.0; packetlib-1.0; mcprotocollib-1.10.2-20160628.203512-2.

How can i fix it? i have looked up on jenkins for the latest mcprotocollib libraries and i haven't found nothing besides those

**Comment by games647** [comment]
You have to build the parent project. It reshades package to this location.

**Comment by games647** [comment]
The child projects version1X imports the different versions of mcprotocollib and moves the the package to a different location.

**Comment by OfficialAName** [comment]
i don't get it, what do you mean by building the parent project. Like create the project path then import the source file in the project?

**Comment by games647** [comment]
This project is now split into subprojects. [The parent project is located at the root folder.](https://github.com/games647/LambdaAttack/blob/master/pom.xml). If you want to compile that project it will trigger a compile to all sub projects. See all the folders. 

The version_X projects imports the library of mcprotocollib and moves the protocol specification to a different location packet.v1_X.....

The core project will be build at the end. It depends on all the version projects and is reponsible for managing the complete project at runtime. (Starting bots, selecting version...). That's like the old version except that the version specification for 1.10 is exported into the subproject v1_10.

**Comment by OfficialAName** [comment]
Here is how it looks like, i don't know if you mean to look this way or.. (sorry for late response, i was busy)
![screenshot from 2016-09-01 18-07-38](https://cloud.githubusercontent.com/assets/18629391/18172754/77a14f0c-706f-11e6-9ec8-17e0d693e41d.png)

**Comment by games647** [comment]
Do you have the latest one? BTW: there is an error in the v1_7 package. Could you show me that one?

**Comment by OfficialAName** [comment]
1. `The import org.spacehq.mc.auth.exception.AuthenticationException cannot be resolved`
2. `AuthenticationException cannot be resolved to a type`
3. `org.spacehq.mc.auth.GameProfile cannot be resolved to a type`
4. `org.spacehq.mc.auth.GameProfile cannot be resolved to a type`

**Comment by games647** [comment]
Try to reset your maven repository, because your authlib version is incorrect.

Do you even compiled it with maven?

**Comment by OfficialAName** [comment]
nono, the error is not from the compile, is when i import the project from github

**Comment by games647** [comment]
You have to compile it once

**Comment by OfficialAName** [comment]
still won't work... idk what i am doing wrong here :( i post a video and show you

**Comment by games647** [comment]
Do you compiled it with Maven?

**Comment by OfficialAName** [comment]
no, i never used maven in my life xD, also, you have the parameters to launch in linux? to use proxy threads server port and how many threads? here is the yt video, https://www.youtube.com/watch?v=slUeHrXfgCw&feature=youtu.be

**Comment by games647** [comment]
You should select Maven, when the project window pop up after clone.

**Comment by OfficialAName** [comment]
oh, ok! but do you have start parameters for linux>?

**Comment by games647** [comment]
You mean to start this program from the command line?

**Comment by OfficialAName** [comment]
yes

**Comment by games647** [comment]
I decided not do so, because this should only be for testing your server. There you don't need automatic environment like a shell

**Comment by games647** [comment]
Sorry

**Comment by OfficialAName** [comment]
oh ok.. but will you implement this feature?

**Comment by games647** [comment]
Because of the above reasons, no.

**Comment by OfficialAName** [comment]
oK:(, now when i imported it using maven, it had 1 error in 1 package.. :(

**Comment by games647** [comment]
I need the error message please.

**Comment by OfficialAName** [comment]
i deleted the project, but the errors was in the folder with version1_0, import spacehq_v_1_0, something like that

**Comment by OfficialAName** [comment]
Ok here i posted all the errors! https://www.youtube.com/watch?v=6MB2r4cac84&feature=youtu.be

**Comment by games647** [comment]
Do you compiled it once? The import paths are only if you compiled it once.

**Comment by games647** [comment]
But it says. Build success.

**Comment by games647** [comment]
What about a TeamViewer session?

**Comment by OfficialAName** [comment]
ok, if you are on
sure

**Comment by games647** [comment]
yes I am

**Comment by OfficialAName** [comment]
ok, so you have skype or?

**Comment by OfficialAName** [comment]
to give you id and pass

**Comment by games647** [comment]
Skype: games647

**Comment by OfficialAName** [comment]
added

**Comment by games647** [comment]
If others have this issue too:

The issue was that Eclipse couldn't detect the classpath change if the version-X are still open. It was fixed by closing it and running "mvn clean install"
