### ISSUE TITLE
Download link and HTTP, SOCK4 Support

### ISSUE THREAD

**Issue by OfficialAName** [games647/LambdaAttack#7]
Could you add a download link please ? And http, ssl, socks4 support?

**Comment by games647** [comment]
HTTP and SSL proxies can be only used for HTTP or HTTPS traffic like the authentication API from Minecraft. For the normal minecraft traffic you have to use SOCKS4/5 proxies which can be already used in LambdaAttack.

**Comment by OfficialAName** [comment]
oh, ok. But, do you add a download link?

**Comment by games647** [comment]
https://github.com/games647/LambdaAttack#downloads

**Comment by OfficialAName** [comment]
thank you ~!, lock pls? xD

**Comment by games647** [comment]
?

**Comment by OfficialAName** [comment]
mark as solved?

**Comment by games647** [comment]
That's a close
